### ISSUE TITLE
BepInEx ConfigEntry extensions missing parameters

### ISSUE THREAD

**Issue by LeeTwentyThree** [SubnauticaModding/Nautilus#317]
https://github.com/SubnauticaModding/Nautilus-Proto/issues/28

Issue mirrored @JKohlman

**Comment by tinyhoot** [comment]
I've looked a bit more into this one.

The issue occurs specifically when using the BepInEx config backend and converting those directly to ModOptions using the `ToModOptions()` extensions. From my testing, this works well for all option types except ChoiceModOptions. As opposed to all other types, their config description does not get converted into a tooltip. Additionally, the value of the option in the menu is set to whatever the first value in the list of acceptable values is, rather than the value that is currently set in the config.

**Comment by MrJumpscare** [comment]
> I've looked a bit more into this one.
> 
> The issue occurs specifically when using the BepInEx config backend and converting those directly to ModOptions using the `ToModOptions()` extensions. From my testing, this works well for all option types except ChoiceModOptions. As opposed to all other types, their config description does not get converted into a tooltip. Additionally, the value of the option in the menu is set to whatever the first value in the list of acceptable values is, rather than the value that is currently set in the config.

This is also likely the cause of [#316](https://github.com/SubnauticaModding/Nautilus/issues/316). The value of the option is indeed set to the first value instead of changing to what is set in the in-game config menu.

**Comment by 32Kallies** [comment]
Can you send a mod file that experiences this issue?

**Comment by tinyhoot** [comment]
I have my config and ModOptions split into two files. Both ChoiceOptions experience the issue. [https://github.com/tinyhoot/AcceleratedStart/blob/c139913c86e8a3af367378cb9a5fd26ccbfae3fa/ConfigModOptions.cs#L13](https://github.com/tinyhoot/AcceleratedStart/blob/c139913c86e8a3af367378cb9a5fd26ccbfae3fa/ConfigModOptions.cs#L13)
The BepInEx config entry is defined [here](https://github.com/tinyhoot/AcceleratedStart/blob/c139913c86e8a3af367378cb9a5fd26ccbfae3fa/Config.cs#L34).

Edit: Sorry, I just now realised you asked for an executable.
[AcceleratedStart-dev.zip](https://github.com/SubnauticaModding/Nautilus/files/11478724/AcceleratedStart-dev.zip)

**Comment by JKohlman** [comment]
Hey yeah, aware of this - I'm doing a comprehensive review of every extension and option type to try and cover any other cases as well. I've been pretty busy but should have some time to work on it this week.
