### ISSUE TITLE
Allow crafting nodes & tabs in the same space

### ISSUE THREAD

**Issue by 32Kallies** [SubnauticaModding/Nautilus#330]
**Describe the feature**
No idea what it is, I got it from Eldritch.

```cs
private static class Test21
        { 
            [HarmonyPatch(typeof(uGUI_CraftingMenu), nameof(uGUI_CraftingMenu.IsGrid))] 
            private static void Postfix(uGUI_CraftingMenu.Node node, ref bool __result)
            { 
                __result = ShouldGrid(node);
            }

            private static bool ShouldGrid(uGUI_CraftingMenu.Node node)
            {
                var craftings = 0;
                var tabs = 0;

                foreach (var child in node)
                {
                    if (child.action == TreeAction.Expand) tabs++;
                    else if (child.action == TreeAction.Craft) craftings++;
                }

                return craftings > tabs;
            }

            [HarmonyPatch(typeof(uGUI_CraftingMenu), nameof(uGUI_CraftingMenu.Collapse))] 
            private static void Postfix(uGUI_CraftingMenu.Node parent)
            {
                if (parent == null) return;

                if (parent.action != TreeAction.Craft) return;

                parent.icon.SetActive(false);
            }
        }

```

**Comment by EldritchCarMaker** [comment]
The initial patch and the ShouldGrid method are used to decide if a specific crafting node should be displayed as a grid or as a single vertical line. Normally in the game if there is even a single tab node in a section then it will force every single node to be completely vertical. This changes that so that it only becomes vertical if there's more tab nodes than crafting nodes. This means that all vanilla crafting trees will remain untouched, but that theoretically you could add a new modded tab node to a crafting section without forcing the entire section to unnecessarily become a straight vertical line.

**Comment by EldritchCarMaker** [comment]
The second patch is there to disable any crafting nodes that are on the same tab as an opened tab node. Normally the game closes any other tab nodes when a new one is opened, but this extends it slightly further to also disable any other crafting nodes when a tab is opened. This also will have no effect on vanilla crafting trees, but it means that a mod could add a tab to a set of crafting nodes without having to deal with overlapping

This does have a decent flaw, however, in that the tabs retain their original position when they're opened, while all the craft nodes disappear. So this means that the tab nodes will basically be floating. 

For example, in a 2x2 grid, 

A, B
C, D

if A, B, and C are all craft nodes, but D is a tab node, if D is opened then A, B, and C will all disappear, but D will remain in the same place, leading to

0 0
0 D

Where the zeroes are simply empty space.

**Comment by 32Kallies** [comment]
What mods can I use to test this?

**Comment by EldritchCarMaker** [comment]
Unfortunately there are currently none public, largely because nautilus itself stops mods from doing it https://github.com/SubnauticaModding/Nautilus/blob/0d0eddaabd900e3cd76dd3ab2186074680a96862/Nautilus/Patchers/CraftTreePatcher.cs#L157
So this check should be removed first for a custom nautilus build, and then a test mod can be made (or you can use the repl console, depending on how much experience you have with the original code

**Comment by MrPurple6411** [comment]
@EldritchCarMaker I put those limitations in place because the only way it doesn't currently MASSIVLY break the visuals when you have them together is using the Radial Tabs mod.

If you are not using the radial tabs mod and do as you are asking and then try and open the new tab node that is horizontally placed it will open right where it is and you then have its sub items overlapping the current nodes which are also there.

One day I will see about reworking the system so that it Only shows the Crafting nodes of the currently opened tab which should fix this issue at which point I will implement your request.
