### ISSUE TITLE
New prefab component utilities

### ISSUE THREAD

**Issue by 32Kallies** [SubnauticaModding/Nautilus#343]
**Describe the feature**
* `PrefabUtils.AddEnergyMixin(???)`
* `PrefabUtils.AddStorageContainer(???)`
* ~~`PrefabUtils.AddEatable(???)` [sic]~~
* Make sure the constructable one is in the right file 

**Purpose**
Reduces repetition of redundant code, allows us to document vanilla features, provide default values, reduce the chance of forgetting important steps, and reduces prefab creation code length by several lines.

**Usage**
Use these methods with GameObject creation.

**Comment by EldritchCarMaker** [comment]
I would much prefer if we didn’t have methods that simply abstracted away adding components. Unless that component is something that requires large amounts of set up (like storage container, and how it requires child object identifiers), I don’t believe we should have it here

This is for a few reasons, firstly because I think it’s likely to discourage people from actually understanding what nautilus is doing in the backend, and not trying to understand what components are or how they work. Secondly because there are much better ways to be doing these types of things that I believe we should be encouraging much more. Thirdly because a lot of these would be methods that are a few simple lines at most, so it would be a very clear candidate to be trimmed down in a future update, and because of that it could break future mods which use it. And all of this, for next to no actual gain. An add eatable method would be like 5 lines of code at most. 

I do think something like an add storage container method could be useful, because it often requires a lot of specific things to work properly, but most components aren’t like that.

**Comment by 32Kallies** [comment]
Yes I agree it could be troublesome if everything becomes too abstract, but the inner workings of all the methods in this class are not something that the average modder really needs or wants to know. It takes a while to reverse engineer some of these classes, often requiring runtime editor for examples of proper setup; we reinvent the wheel every time we use some of these. This has gain in the sense of A) documenting properties, B) providing recommended/default values, C) condensing several lines into a few, D) ensuring all required values are set and E) removing the desire to set  obsolete/unused/unnecessary/private fields. Do you not think condensing code is a benefit?

What better ways of doing this would you suggest?

**Comment by EldritchCarMaker** [comment]
> Yes I agree it could be troublesome if everything becomes too abstract, but the inner workings of all the methods in this class are not something that the average modder really needs or wants to know. 
We disagree here. I believe that these are things that modders *should* understand the inner workings of, especially when said inner workings amount to 

- add component
- set fields 

These are basic parts of learning to mod this game, and are fundamental to any form of advanced modding (or even just anything beyond tweaking the occasional value). We shouldn’t be abstracting everything away just because it takes more than two lines to do. Next thing you know we have people asking us to put in a `TurnAllRenderersRed` method because they don’t know how to get the components of an object.

A, B, and D, and E could all be covered elsewhere. We’ve been thinking of having game-wide documentation for a while now, and that could be significantly better than trying to force the documentation into unnecessary methods like this. Will continue the discussion about documentation for the game in discord

As for point C, I don’t believe that some of these offer enough of a condensed version to offset the issues I brought up earlier.

**Comment by 32Kallies** [comment]
This only covers basics, for basic use cases. Anything complicated still requires more than a single method. No reason to make people write so much for commonly used purposes.

**Comment by 32Kallies** [comment]
cutting eatable because I agree that some things ARE unnecessary but I will still add some

**Comment by 32Kallies** [comment]
#350
