### ISSUE TITLE
ModID extra info not showing correctly.

### ISSUE THREAD

**Issue by MrPurple6411** [SubnauticaModding/Nautilus#477]
**Describe the bug**
When using Nautilus to show modid on the tooltips it is showing the number (number) of the techtype instead of name (number)

**To Reproduce**
Turn on mod name and itemid in options menu.

**Expected behavior**
Techtype string and number are shown

**Screenshots**
![image](https://github.com/SubnauticaModding/Nautilus/assets/7858500/ad155688-42c9-4919-8a6b-bffc3da99ab5)

**Comment by Metious** [comment]
This is a known issue and it's caused when the mod that adds that tech type is loaded before Nautilus. Just add the following to your plugin entry point class
```cs
[BepInDependency("com.snmodding.nautilus")]
```
Then your tech types will show up correctly.

I haven't looked into why or how it registers and tracks the prefabs correctly, but somehow the name of the enum is lost because of the loading order.

**Comment by MrPurple6411** [comment]
Anyone having this issue is having it because they forgot to put the dependency attribute.
And anyone who is having said issue due using SMLHelper is also self-inflicting it.
