### ISSUE TITLE
Anti-Piracy

### ISSUE THREAD

**Issue by ReallyDudeQuestionMark** [SubnauticaModding/Nautilus#563]
Why even implement an anti-piracy measure if all I have to do to get rid of the overlay is launch the game, load a save file and exit to the menu to get rid of it lol?

You have caused an issue with one or two of my other mods that don't like going back to the main menu a second time so thanks for that.

**Comment by VaelophisNyx** [comment]
Really no mod should be doing antipiracy code at all, there's no need to white knight for a billion dollar company, and it has ZERO effect on modders if someone does pirate the game
otherwise 99% of anitpiracy in mods is literally just malware and potentially illegal itself, not just morally bankrupt

**Comment by 32Kallies** [comment]
I somewhat agree with the sentiment but we don't even have any anti-piracy measures lol

**Comment by RamuneNeptune** [comment]
You can forward your feedback to: jeff@amazon.com.

Best regards,
Jeff Ramune Bezos
